services:
  - type: web
    name: andar-bahar-backend
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        sync: false
      - key: FARCASTER_APP_URL
        sync: false
      - key: SOCKET_URL
        sync: false
    healthCheckPath: /health
    autoDeploy: true 